language: ruby
rvm:
 - 2.5.0
env:
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
before_script:
  - cp config/database.travis.yml config/database.yml
  - cp config/environments/default.yml.example config/environments/default.yml
  - psql -c 'create database mei_test' -U postgres